// QA Instance Apache 9 development purpose
/*
const REST_CONFIG = {
  BASEURL: "65.1.238.219",
  METHOD: "http",
  PORT: 9080,
  RESTAPPNAME: "teckonnect",
};
*/

// Arvind Laptop
/*
const REST_CONFIG = {
  BASEURL: "127.0.0.1",
  METHOD: "http",
  PORT: 8080,
};
*/

// Crayond
const REST_CONFIG = {
  // BASEURL: "dev-enliteu-api.crayond.com",
  // METHOD: "https",
  // PORT: 443,
  // RESTAPPNAME: "teckonnect",

  BASEURL: "dev-enliteu-api.crayond.com",
  METHOD: "https",
  BASEURL_AUTH: "dev-auth-enliteu.crayond.com",

  FIREBASE_API_KEY: "AIzaSyB-aEYjSIMXtAI7Z7jILhrR81quV9L319s",
  FIREBASE_AUTH_DOMAIN: "enliteu-crayond.firebaseapp.com",
  FIREBASE_PROJECT_ID: "enliteu-crayond",
  FIREBASE_STORAGE_BUCKET: "enliteu-crayond.appspot.com",
  FIREBASE_MESSAGING_SENDER_ID: "16677502716",
  FIREBASE_APP_ID: "1:16677502716:web:8791605d0ee88792912179",
  FIREBASE_MEASUREMENT_ID: "G-T4PFZZTKZV",
  FIREBASE_VAPIDKEY: "BBhlYcWVhn72B-x0BD23CdxbXBuHC-w53LEaYWlgavcDZtwNLKF4U8WxkPWTVKq1Cr9dJodk9eijUmeBiCGucu8",
  SENTRY_AUTH_TOKEN: "AAAAA-IOfvw:APA91bHD3MRQVpB07MmveEhJsATsXulXsRX_zOEL_8ceoPws4BDgeaRYcFwqb0ViQ1KbL2_zZ_HaTxRla6gbN0XCQyNugouqBKAwSFaGOSnyRrz6T_oZr3P0uFplJBp2IqNq2hglcwmy",
};

// QA Instance Apache 9 Demo purpose
/*
const REST_CONFIG = {
  BASEURL: "65.1.238.219",
  METHOD: "http",
  PORT: 9080,
  RESTAPPNAME: "teckonnecteep",
};
*/

// Demo Instance Apache 10
/*
const REST_CONFIG = {
  BASEURL: "13.235.139.216",
  METHOD: "http",
  PORT: 9080,
  RESTAPPNAME: "teckonnect",
};
*/

const URL_CONFIG = {
  LOGIN: "/api/auth/signin",
  LOGOUT: "/api/auth/signout",
  FORGOTPASSWORD: "/api/auth/forgotpassword",
  RESETPASSWORD: "/api/auth/resetpassword",
  UPDATEPASSWORD: "/users/updatepassword",
  ALLUSERS: "/users",
  GETALLUSERS: "/users/activeuser",
  GETUSER: "/users/user",
  GET_USERS_BY_DEPARTMENT: "/users/getusersbydepartment",
  IMPORT_USERS: "/excels/import",
  UPDATEUSERSIGNATURE: "/users/signatureuploadurl",
  ALLDEPARTMENTS: "/departments/activedepartment",
  ADDDEPARTMENT: "/departments/department",
  DEPT_USERS: "/users/getusersbydepartmentlist",
  HASHTAGALL: "/hashtags",
  ADDHASHTAG: "/hashtags/hashtag",
  ACTIVE_HASHTAG: "/hashtags/activehashtag",
  HASHTAG_BULK_UPDATE: "/hashtags/activehashtag",
  ALLROLES: "/roles",
  ADDROLE: "/roles/role",
  ROLES_BULK_UPDATE: "/users/updateroles",
  GET_ROLE_PERMISSIONS: "/roleScreenMappings/rolescreenroleid",
  ROLE_SCREEN_MAPPING: "/roleScreenMappings/roleScreenMapping",
  USER_PERMISSION: "/roleScreenMappings/rolescreenroleid",
  ALLBADGES: "/badges/activebadge",
  CREATE_BADGE: "/badges/badge",
  LIBRARY_BADGES: "/library/allbadge",
  RECOGNIZE_BADGE: "/badges/assignbadge",
  MY_BADGES: "/badges/mybadges",
  BADGE_BULK_UPDATE: "/badges/badge",
  SHARE_WALL: "/socialwall/sharewall",
  CREATE_AWARD: "/awards/award",
  LIBRARY_AWARDS: "/library/allawards",
  ALLAWARDS: "/awards/activeaward",
  AWARD_BULK_UPDATE: "/awards/award",
  SPOT_AWARD: "/awards/spotaward",
  NOMINATOR_AWARDS: "/awards/nominatorview",
  RECOGNIZE_SPOT_AWARD: "/awards/spotawardrecognize",
  NOMINATE_DO_AWARD: "/awards/donomination",
  MY_AWARDS: "/awards/myawards",
  NOMINATE_AWARD: "/awards/nominateaward",
  MY_NOMINATIONS: "/awards/mynominations",
  NOMINATIONS_LIST: "/awards/listnominations",
  MY_APPROVALS: "/awards/myapprovals",
  APPROVE_RECOGNISED_AWARDS: "/awards/doapprove",
  MANAGE_AWARDS: "/awards/manage",
  CERTIFICATE: "/certificates/certificate",
  ALL_CERTIFICATE: "/certificates/all",
  ASSIGN_CERTIFICATE: "/certificates/assigncertificate",
  MY_CERTIFICATES: "/certificates/mycertificate",
  CREATE_TEMPLATE_ECARD: "/ecards/ecard",
  GET_TEMPLATE_ECARD: "/ecards/templates",
  CREATE_TEMPLATE_MESSAGE: "/ecards/message",
  GET_TEMPLATE_MESSAGE: "/ecards/messages",
  GET_SCHEDULETIME: "/ecards/scheduletime",
  SCHEDULE_BIRTHDAY: "/ecards/birthdaySettings",
  DELETE_TEMPLATE_CARD: "/ecards/deletetemplate",
  DELETE_TEMPLATE_MESSAGE: "/ecards/deletemessage",
  ALL_ECARDS: "/ecards/alltemplates",
  ALL_MESSAGES: "/ecards/allmessages",
  ANNIVERSARY_ECARD: "/ecards/anniversary",
  GET_ANNIVERSARY_YEARS: "/ecards/allyear",
  DELETE_YEAR: "/ecards/deleteyearinterval",
  SCHEDULE_ANNIVERSARY: "/ecards/anniversarysettings",
  SEND_ECARD: "/ecards/sendecard",
  ECARD_INBOX: "/ecards/mycards",
  ECARD_LIKE: "/ecards/likecards",
  READ_ALL_ECARD: "/ecards/readall",
  REFRESH_TOKEN: "/api/auth/refreshtoken",
  SOCIALWALL_GET_USERLIST: "/socialwall/userlist",
  SOCIALWALL_HASTAG_LIST: "/socialwall/hashtagList",
  SOCIALWALL_LIST: "/socialwall/wall",
  SOCIALWALL_SINGLE: "/socialwall/wallid",
  SOCIALWALL_LIKE: "/socialwall/likepost",
  SOCIALWALL_DISLIKE: "/socialwall/deletelikepost",
  SOCIALWALL_COMMENT: "/socialwall/comments",
  SOCIALWALL_COMMENT_LIST: "/socialwall/commentslist",
  SOCIALWALL_REPLY: "/socialwall/commentsreply",
  IDEA: "/ideas/idea",
  IDEA_READ_UNREAD: "/ideas/idearead",
  IDEA_IMPORTANT_UNIMPORTANT: "/ideas/ideafavorites",
  IDEA_READ_ALL: "/ideas/ideareadall",
  IDEA_LIKE_DISLIKE: "/ideas/idealikes",
  IDEA_BY_ID: "/ideas/ideaid",
  IDEA_COMMENT: "/ideas/ideacomments",
  MY_IDEAS: "/ideas/myidea",
  FORUM: "/forums/forum",
  GET_FORUM_LIST: "/forums/forum",
  FORUM_FOLLOWING: "/forums/forumfollowing",
  FORUM_READ_UNREAD: "/forums/forumread",
  FORUM_READ_ALL: "/forums/forumreadall",
  FORUM_COMMENTS: "/forums/comments",
  FORUM_BY_ID: "/forums/forumid",
  MY_FORUMS: "/forums/myforum",
  ENLITE_FORUM: "/forums/forumlikes",
  FORUM_COMMENT_LIKE_UNLIKE: "/forums/commentlikes",
  FORUM_DELETE_COMMENT: "/forums/deletecomments",
  FORUM_COMMENTS_REPLY: "/forums/commentsreply",
  SURVEY: "/surveys/survey",
  PENDING_SURVEY: "/surveys/surveypending",
  SHOW_SURVEY: "/surveys/surveyshow",
  MY_SURVEY: "/surveys/mysurvey",
  SURVEY_RESULT: "/surveys/surveyresult",
  SURVEY_RESPONSE: "/surveys/response",
  SURVEY_QUESTIONBANK: "/surveys/questionbank",
  SURVEY_SUBMIT: "/surveys/submit",
  SURVEY_IMPORTANT_UNIMPORTANT: "/surveys/surveyimportant",
  SURVEY_MODIFY: "/surveys/modify",
  SURVEY_BY_ID: "/surveys/surveyid",
  SURVEY_REPUBLISH: "/surveys/republish",
  SURVEY_ACCEPT_RESPONSE: "/surveys/toggleresponse",
  POLL: "/polls/poll",
  CLOSED_POLLS: "/polls/closedpoll",
  ACTIVE_POLLS: "/polls/activepoll",
  POLL_GET_BY_ID: "/polls/pollid",
  POLL_SUBMIT: "/polls/submitpoll",
  POLL_RESPONSE: "/polls/pollresponse",
  DASHBOARD_INDEX: "/dashboards/index",
  USER_DASHBOARD: "/dashboards/dashboardUser",
  REWARDS_RECOGNITION: "/dashboards/rewardrecognition",
  HALL_OF_FAME: "/dashboards/hall",
  GET_POINTS: "/points/point",
  NOTIFICATIONS_BY_ID: "/notification/notification",
  NOTIFICATIONs_READ: "/notification/read",
  NOTIFICATIONs_DELETE: "/notification/delete",
  TOUR: "/users/tour",
  TOUR_UPDATE: "/users/projecttour",
  SEARCH: "/users/search",
  TOKEN_UPDATE: "/users/set_device_token",

  AUTH_LOGIN_URL: "/api/v1/auth/login",
  AUTH_REST_PASSWORD_URL: "/api/v1/auth/reset_password",
  AUTH_FORGOT_PASSWORD_URL: "/api/v1/auth/forgot_password",
  AUTH_FORGOT_PASSWORD_EMAIL_URL: "/api/v1/auth/forgot_password_mail",
  RESETPASSWORD_AUTH: "/api/auth/reset_password",
};

export { REST_CONFIG, URL_CONFIG };
